version: "3"
# também é possível usar somente o docker-compose sem os dockerfile, desde que todas as configurações viessem para este arquivo

services:
# ver as anotações do web-front e seguir o mesmo padrão
  server-back:
    container_name: server-back-nlw
    build: ./server
    ports:
      - 3333:3333
    environment:
    - DATABASE_URL="file:./dev.db"
    depends_on:
    - db

  db:
  # neste formato já cria a base necessária para o banco de dados - confirmar na documentação se está com as portas corretas e base necessária
    container_name: db-nlw
    image: postgres:alpine3.15
    restart: always
    ports:
      - 8080:8080

  web-front:
    container_name: web-front-nlw
    build: ./web
    # momento que constroi a imagem do front com o nome definido acima. Buscando dentro da pasta ./web um dockerfile.
    tty: true
    # Mesmo que `docker run -t
    stdin_open: true
    # mesmo que `docker run -i`
    command: bash
    # as primeiras três linhas acima, em conjunto, permitem acessar de modo interativo no container, com exec -it 'container_name' bash
    restart: always
    volumes:
      # Lista de volumes (diretórios) mapeados de fora para dentro do container
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /src conforme definido no dockerfile do front
      - ./:/src
    environment:
      - VITE_API_URL=http://localhost:3333
      # ??? buscar na documentação do docker relacionado ao vite.?????
    ports:
      - 3001:3000
      # porta do lado direito é do container, noc caso do node é 3000.
    depends_on:
      - server-back

networks:
  default:
    name: nlw

  # docker-compose up 

  # estudar sobre o heroku - bloco 25.
  # é possível subir vários containers ao mesmo tempo, ou será necessário conectá-los com link dentro do heroku?

# As chaves `tty`, `stdin_open` e `command` fazem com que o container fique
# rodando em segundo plano, bem como tornam possível o uso do comando
# `docker attach`, já deixando o terminal atual acoplado ao container, direto
# no bash. Apesar disso, utilizar o attach mais de uma vez irá replicar o
# terminal, portanto é melhor utilizar o comando `docker exec`.