version: "3"

services:
  server-back:
    container_name: server-back-nlw
    build: ./server
    image: server-back
    ports:
      - 3333:3333
    environment:
    - DATABASE_URL="file:./dev.db"

  db:
    container_name: db-nlw
    image: postgres:alpine3.15
    restart: always
    ports:
      - 8080:8080

  web-front:
    container_name: web-front-nlw
    build: ./web
    image: web-front
    tty: true
    stdin_open: true
    environment:
      - VITE_API_URL=http://localhost:3333
    ports:
      - 3001:3001
    depends_on:
      - "server-back"
      - "db"

networks:
  default:

  